version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    profiles:
      - app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    profiles:
      - app
  backend-tests:
    build: ./backend
    entrypoint: ["npm", "test"]
    profiles:
      - test
